name: 'my-pipeline'

on:
  push:
    branches:
    - 'main'

concurrency: ${{github.repository}}

jobs:
  build:
  
    permissions:
      contents: 'write'
      id-token: 'write'
        
    runs-on: 'ubuntu-latest'
    steps:

    - name: Git checkout
      id: git-checkout
      uses: actions/checkout@v4

    - name: authenticate gcloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'house-price-prediction-439306'
        # workload_identity_provider: 'projects/898780699062/locations/global/workloadIdentityPools/my-workload-pool/providers/my-workload-provider'
        service_account: 'for-github-action-2@house-price-prediction-439306.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.FOR_GCP }}

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: export gcloud related env variable
      run: export CLOUDSDK_PYTHON="/usr/bin/python3"

    - name: install python SDK for google
      run: pip install --upgrade google-api-python-client google google.cloud google-cloud-aiplatform scikit-learn pandas==2.0.3

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: house-price-prediction-439306
        service_account_key: ${{ secrets.FOR_GCP }}

    - name: fine-tune model
      id: fine-tune-model  # Removed space in ID
      env:
        GOOGLE_CREDENTIALS: ${{secrets.FOR_GCP}}
      run: python model-pipeline.py --project_id house-price-prediction-439306 --staging_bucket gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62 --train_dataset_url gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62/train_data.csv --test_dataset_url gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62/test_data_no_label.jsonl
