
name: 'my-pipeline'

on:
  push:
    branches:
      - 'main'
    paths:
      - './'

concurrency: ${{github.repository}}

jobs:
  build:
    name: 'pipeline job'
    runs-on: 'ubuntu-latest'
    steps:
    
      - name: Git checkout
        id: git-checkout
        uses: actions/checkout@v4

      - name: fine-tune model
        id: fine-tune model
        env:
          GOOGLE_CREDENTIALS: ${{secrets.FOR_GCP}}
        run: python model-pipeline.py --project_id house-price-prediction-439306 --staging_bucket gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62 --train_dataset_url gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62/train_data.csv --test_dataset_url gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62/test_data_no_label.jsonl

