name: 'my-pipeline'

on:
  push:
    branches:
    - 'main'

concurrency: ${{github.repository}}

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:

    - name: Git checkout
      id: git-checkout
      uses: actions/checkout@v4

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: house-price-prediction-439306
        service_account_key: ${{ secrets.FOR_GCP }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    # - name: build and push the docker image
    #   env:
    #     GOOGLE_PROJECT: ${{ secrets.FOR_GCP }}
    #   run: |
    #     gcloud auth configure-docker us-central1-docker.pkg.dev
    #     docker build -t us-central1-docker.pkg.dev/$GO0GLE_PROJECT/demo/nginx:latest .
    #     docker push us-central1-docker.pkg.dev/$G00GLE_PROJECT/demo/nginx:latest

    - name: fine-tune model
      id: fine-tune-model  # Removed space in ID
      env:
        GOOGLE_CREDENTIALS: ${{secrets.FOR_GCP}}
      run: python model-pipeline.py --project_id house-price-prediction-439306 --staging_bucket gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62 --train_dataset_url gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62/train_data.csv --test_dataset_url gs://cloud-ai-platform-07b92f9d-de58-4aea-81a9-1566224d6a62/test_data_no_label.jsonl
